### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by mhesselbarth** [ropensci/getCRUCLdata#10]
Hey, 

It seems like the package was recently remove from CRAN. Are there any plans to fix the errors and resubmit the package? 

Thanks a lot.

**Comment by adamhsparks** [comment]
I hadn't planned on it. It was removed because of [issues with](https://github.com/r-lib/rappdirs/issues/40) _rappdirs_, which I'd used for years without issue. I can't tell that _rappdirs_ have addressed the issue and while I could use the native R app directories, that limits the package to R>4.1 (IRRC). Since it still works just as it did before CRAN threw a snit and removed it, I've elected to just leave as-is here with the installation instructions in the README being current and accurate.

**Comment by adamhsparks** [comment]
It’s back on CRAN now. https://cran.r-project.org/package=getCRUCLdata

**Comment by adamhsparks** [comment]
Sorry. Removed again. It won’t be going back a third time

**Comment by mhesselbarth** [comment]
Fair, I get it :) Thanks for trying at least
